BuscarMedico/BuscarMedico/Controllers/EspecialidadeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BuscarMedico.Models;
using System.Data;

namespace BuscarMedico.Controllers
{
    public class EspecialidadeController : Controller
    {
        private Entitiescademeumedicobd db = new Entitiescademeumedicobd();

        public ActionResult Index()
        {
            var especialidade = db.especialidades;

            return View(especialidade);
        }

        //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

        public ActionResult Adicionar()
        {
            return View();
        }

        //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

        [HttpPost]
        public ActionResult Adicionar(especialidades especialidade)
        {
            if (ModelState.IsValid)
            {
                db.especialidades.Add(especialidade);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(especialidade);
        }

        //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

        public ActionResult Editar(long id)
        {
            especialidades especialidade = db.especialidades.Find(id);
            return View(especialidade);
        }


        //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


        [HttpPost]
        public ActionResult Editar(especialidades especialidade)
        {
            if (ModelState.IsValid)
            {
                db.Entry(especialidade).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(especialidade);
        }

        //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


        public string Excluir(long id)
        {
            try
            {
                especialidades especialidade = db.especialidades.Find(id);
                db.especialidades.Remove(especialidade);
                db.SaveChanges();
                return Boolean.TrueString;
            }
            catch
            {
                return Boolean.FalseString;
            }
        }

    }
}

BuscarMedico/BuscarMedico/Controllers/MedicosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BuscarMedico.Models;
using System.Data;
using System.StubHelpers;

namespace BuscarMedico.Controllers
{
    public class MedicosController : Controller
    {
        private Entitiescademeumedicobd db = new Entitiescademeumedicobd();  // CRIANDO UMA INSTANCIA DE COMUNICAÇÃO DO MODELO COM O BANCO DE DADOS..


        public ActionResult Index() // CHAMA O LINK P/ SER CLICADO P/ ABRIR O FORMULARIO ...
        {
            // OBTENDO UMA LISTA COM TODOS OS MEDICOS CADASTRADOS NO BANCO DE DADOS...
            // LISTANDO TODOS MEDICOS E OBTENDO SUAS RESPECTIVAS ESPECIALIDADES E CIDADES.. 
            var medico = db.medicos.Include("Cidades").Include("Especialidades"); //.ToList(); // "LISTA"
            return View(medico);
        }

        /// /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        // CADASTRAR MEDICOS //
        public ActionResult Adicionar()
        { // ADCIONAR NOVO MEDICO.. VIEWBAG = TRANSFERE DADOS DOS CONTROLES P/ AS VIEWS, SELECTLIST REPRESENTA UM COMBOBOX...
            ViewBag.IDCidade = new SelectList(db.cidades, "IDCidade", "Nome");
            ViewBag.IDEspecialidade = new SelectList(db.especialidades, "IDEspecialidade", "Nome");
            // OBS: ESSA ACTION MOSTRA O FORMULARIO
            return View();

            /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

        }
        [HttpPost] // DIZ AO FRAMEWORK QUAL ACTION ELE DEVE EXECUTAR QUANDO A REQUISISÇÃO POSSUIR O " VERBO POST "
        public ActionResult Adicionar(medicos medico)
        {
            if (ModelState.IsValid) // TESTA SE O FORMULARIO É VALÍDO ..
            {
                db.medicos.Add(medico); // SE VALÍDO, ADICIONA ..
                db.SaveChanges(); // SALVA OS DADOS DO FORMULARIO ..
                return RedirectToAction("Index"); // E RETORNA P/ A ACTION INDEX ..
            }
            ViewBag.IDCidade = new SelectList(db.cidades, "IDCidade", "Nome", medico.IDCidade); // ADICIONANDO A CIDADE DO MEDICO NA LISTA
            ViewBag.IDEspecialidade = new SelectList(db.especialidades, "IDEspecialidades", "Nome", medico.IDEspecialidade); // ADICIONANDO A ESPECIALIDADE DO MEDICO..

            return View(medico);
            // OBS: ESSA ACTION ENVIA O FORMULARIO
        }

        ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        // EDITAR DADOS DOS MEDICOS CADASTRADOS //
        public ActionResult Editar(long id)
        {
            medicos medico = db.medicos.Find(id);
            ViewBag.IDCidade = new SelectList(db.cidades, "IDCidade", "Nome", medico.IDCidade);
            ViewBag.IDEspecialidade = new SelectList(db.especialidades, "IDEspecialidade", "Nome", medico.IDEspecialidade);

            return View(medico);
            // EDITO OS DADOS ...
        }

        //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

        [HttpPost]
        public ActionResult Editar(medicos medico)
        {                                          // VERIFICA ...
            if (ModelState.IsValid)  // SE TIVER OK MANDA AS INFORMAÇÕES EDITADAS PARA O SERVIDOR..
            {
                db.Entry(medico).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            // MANDA P/ O SERVIDOR ....
            ViewBag.IDCidade = new SelectList(db.cidades, "IDCidade", "Nome", medico.IDCidade);
            ViewBag.IDEspecialidade = new SelectList(db.especialidades, "IDEspecialidade", "Nome", medico.IDEspecialidade);
            return View(medico);
        }

        /// //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        // EXCLUIR DADOS DOS MEDICOS CADASTRADOS //
        /*   [HttpGet]
           public ActionResult Excluir(long id) // DELETA MEDICOS CADASTRADOS ...
           {
               medicos medico = db.medicos.Find(id);
               if (medico != null)
               {
                   db.medicos.Remove(medico);
                   db.SaveChanges();
               }
               return RedirectToAction("Index");
           }*/

        //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

        public string Excluir(long id)  // DELETA MEDICOS CADASTRADOS ...
        {
            try
            {
                medicos medico = db.medicos.Find(id);
                db.medicos.Remove(medico);
                db.SaveChanges();
                return Boolean.TrueString;
            }
            catch
            {
                return Boolean.FalseString;
            }
        }

    }
}

BuscarMedico/BuscarMedico/Views/Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Cadê Meu Medico - @ViewBag.Title</title> <!--ViewBag MOSTRA NAS PAGINAS O VALOR PREDEFINIDO..-->
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" /> <!--CHAMANDO O BOOTSTRAP CSS-->
    <style>
        body {
            padding: 60px;
        }

        #cademeumedico {
            color: ButtonFace;
            font-style: oblique;
            font-size: xx-large;
        }

        li:hover {
            background-color: #0094ff;
        }

        img {
            margin-top: 20px;
            margin-bottom: -130px;
        }

        footer {
            margin-left: 800px;
            margin-bottom: 10px;
        }

        #coracao {
            color: #ff0000;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="~/" id="cademeumedico">
                    Buscar Médico  <span class="glyphicon glyphicon-search"></span>
                </a>
            </div>
            <div class="collapse navbar-collapse" id="topo">
                <ul class="nav navbar-nav">
                    <li class="navbar"><a href="~/">Página Inicial</a></li>
                    <li id="menuMedicos">@Html.ActionLink("Médicos", "Index", "Medicos")</li> <!--ADICIONANDO UM NOVO LINK NO TOPO DA PAGINA QUE LEVA AO CADASTRO DE MEDICOS-->
                    <li id="menuCidade">@Html.ActionLink("Cidades", "Index", "Cidades")</li>
                    <li id="menuEspecialidade">@Html.ActionLink("Especialidades", "Index", "Especialidade")</li>
                </ul>
            </div>

        </div>

    </div>
    <div class="container">
        @RenderBody() <!--RENDERIZA OS CODIGOS DAS PAGINAS NESSE LAYOUT PADRÃO-->
    </div>

    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>By Buscar Médico <span class="glyphicon glyphicon-heart" id="coracao"></span> &copy; @DateTime.Now.Year - Todos os direitos reservados</p>
            </div>
        </div>

    </footer>

    <script src="@Url.Content("~/Scripts/jquery-2.1.4.min.js")"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")"></script>
    @RenderSection("script", required: false) <!--DEFINE SEÇÕES, ONDE DETERMINADO CODIGO SERÁ RENDERIZADO.. SEÇÃO ONDE OS SCRIPTS SERÃO RENDERIZADOS ...-->

</body>
</html>