BuscarMedico/BuscarMedico/Models/cidades.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuscarMedico.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class cidades
    {
        public cidades()
        {
            this.medicos = new HashSet<medicos>();
        }
    
        public int IDCidade { get; set; }

        [Required(ErrorMessage = "Campo obrigatorio")]
        [StringLength(50, ErrorMessage = "O nome deve possuir no maximo 50 caracteres")]
        public string Nome { get; set; }
    
        public virtual ICollection<medicos> medicos { get; set; }
    }
}

BuscarMedico/BuscarMedico/Controllers/CidadesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BuscarMedico.Models;
using System.Data;

namespace BuscarMedico.Controllers
{
    public class CidadesController : Controller
    {
        private Entitiescademeumedicobd db = new Entitiescademeumedicobd(); // CRIANDO UMA INSTANCIA DE COMUNICAÇÃO DO MODELO COM O BANCO DE DADOS..

        public ActionResult Index()
        {
            var cidade = db.cidades;

            return View(cidade);
        }

        /// //////////////////////////////////////////////////////////////////////////////////////////////////////////
        // CADASTRAR CIDADE //
        public ActionResult Adicionar()
        {

            return View();
            // ACTION MOSTRA O FORMULARIO
        }

        /// ///////////////////////////////////////////////////////////////////////////////////////////////////////////
        // POSTA OS DADOS P/ O SERVIDOR //
        [HttpPost]
        public ActionResult Adicionar(cidades cidade)
        {
            if (ModelState.IsValid)
            {
                db.cidades.Add(cidade);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cidade);
        }

        ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        public ActionResult Editar(long id)
        {
            cidades cidade = db.cidades.Find(id);
            return View(cidade);
        }

        ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        [HttpPost]
        public ActionResult Editar(cidades cidade)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cidade).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cidade);
        }

        ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

        public string Excluir(long id)
        {
            try
            {
                cidades cidade = db.cidades.Find(id);
                db.cidades.Remove(cidade);
                db.SaveChanges();
                return Boolean.TrueString;
            }
            catch
            {
                return Boolean.FalseString;
            }
        }

    }
}

BuscarMedico/BuscarMedico/Views/Cidades/Adicionar.cshtml
@model BuscarMedico.Models.cidades

@{
    ViewBag.Title = "Adicionar";
}

<h2>Adicionar nova cidade</h2>

@using (Html.BeginForm("Adicionar", "Cidades", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Dados cidade</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Nome)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Nome, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Nome)
        </div>
        <br />
        <p>
            <input type="submit" class="btn btn-primary" value="Salvar" />
        </p>
    </fieldset>
}
<!--
colocar o arrobasection Scripts{
    <script>
        $("#menuCidades").addClass("active");
    </script>
}
-->
<div>
    @Html.ActionLink("Voltar", "Index")
</div>

BuscarMedico/BuscarMedico/Views/Cidades/Editar.cshtml
@model BuscarMedico.Models.cidades

@{
    ViewBag.Title = "Editar";
}

<h2>Editar cidade</h2>

@using (Html.BeginForm("Editar", "Cidades", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Dados da cidade</legend>

        @Html.HiddenFor(model => model.IDCidade) <!--Adicionado para editar-->

        <div class="editor-label">
            @Html.LabelFor(model => model.Nome)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Nome, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Nome)
        </div>
        <br />
        <p>
            <input type="submit" value="Gravar" class="btn btn-primary" />
        </p>

    </fieldset>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

BuscarMedico/BuscarMedico/Views/Cidades/Excluir.cshtml
@model BuscarMedico.Models.cidades

@{
    ViewBag.Title = "Excluir";
}

<h2>Excluir</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>cidades</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.IDCidade)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IDCidade)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Nome)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Nome)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

BuscarMedico/BuscarMedico/Views/Cidades/Index.cshtml
@model IEnumerable<BuscarMedico.Models.cidades>

@{
    ViewBag.Title = "Cidades";
}

<h2></h2>

<p>
    @Html.ActionLink("Adicionar nova cidade", "Adicionar", null, new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            CIDADES
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.ActionLink("Editar", "Editar", new { id = item.IDCidade })<span class="glyphicon glyphicon-pencil"></span> |
                @Html.ActionLink("Excluir", "Excluir", new { id = item.IDCidade }, new { @class = "excluir" })<span class="glyphicon glyphicon-trash"></span>
            </td>
        </tr>
    }

</table>